# Generated by Django 2.1.5 on 2019-01-23 14:00

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('tipo', multiselectfield.db.fields.MultiSelectField(choices=[('Diretor', 'Diretor'), ('Ator', 'Ator')], max_length=12, verbose_name='Atividade')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personagem', models.CharField(blank=True, max_length=150, null=True, verbose_name='Personagem')),
                ('principal', models.BooleanField(default=False, verbose_name='Principal ?')),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Artista')),
            ],
            options={
                'verbose_name': 'Elenco',
                'verbose_name_plural': 'Elencos',
                'ordering': ['ator', 'principal'],
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título em Português')),
                ('titulo_original', models.CharField(max_length=150, verbose_name='Título Original')),
                ('sinopse', models.TextField(verbose_name='Sinopse')),
                ('classificacao', models.CharField(choices=[('L', 'Livre'), ('10', 'Não recomendado para menores de 10 anos'), ('12', 'Não recomendado para menores de 12 anos'), ('14', 'Não recomendado para menores de 14 anos'), ('16', 'Não recomendado para menores de 16 anos'), ('18', 'Não recomendado para maiores de 18 anos')], max_length=2, verbose_name='Classificação Indicativa')),
                ('duracao', models.TimeField(verbose_name='Duração')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano de Lançamento')),
                ('pais', models.CharField(max_length=150, verbose_name='País')),
                ('diretor', models.ManyToManyField(to='core.Artista')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Gênero',
                'verbose_name_plural': 'Gêneros',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor da Locação')),
            ],
            options={
                'verbose_name': 'Tipo de Mídia',
                'verbose_name_plural': 'Tipos de Mídias',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.ManyToManyField(to='core.Genero'),
        ),
        migrations.AddField(
            model_name='elenco',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Filme'),
        ),
        migrations.AlterUniqueTogether(
            name='elenco',
            unique_together={('filme', 'ator')},
        ),
    ]
