# Generated by Django 2.1.5 on 2019-02-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'ordering': ['estado__nome', 'nome'], 'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterField(
            model_name='itemlocacao',
            name='nova_data_devolucao',
            field=models.DateField(blank=True, null=True, verbose_name='Nova Data de Devolução'),
        ),
    ]
