# Generated by Django 2.1.5 on 2019-01-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependente',
            name='codigo',
            field=models.CharField(default='0', max_length=150, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='dependentes',
            field=models.ManyToManyField(related_name='clientes', related_query_name='cliente', to='core.Dependente'),
        ),
    ]
