# Generated by Django 2.1.5 on 2019-02-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
