# Generated by Django 2.1.5 on 2019-01-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='Nome')),
                ('capital', models.BooleanField(default=False, verbose_name='Capital ?')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['nome', 'estado'],
            },
        ),
        migrations.CreateModel(
            name='Distribuidora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=150, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
                ('contato', models.CharField(max_length=150, verbose_name='Pessoa de Contato')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Distribuidora',
                'verbose_name_plural': 'Distribuidoras',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('complemento', models.CharField(max_length=60, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=30, verbose_name='Bairro')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Cidade')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['logradouro', 'numero', 'cidade'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True, verbose_name='Nome')),
                ('sigla', models.CharField(max_length=30, unique=True, verbose_name='Sigla')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(max_length=10, verbose_name='Prefixo')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('tipo', models.CharField(choices=[('L', 'Livre'), ('10', 'Não recomendado para menores de 10 anos'), ('12', 'Não recomendado para menores de 12 anos'), ('14', 'Não recomendado para menores de 14 anos'), ('16', 'Não recomendado para menores de 16 anos'), ('18', 'Não recomendado para maiores de 18 anos')], max_length=15, verbose_name='Tipo de Telefone')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
                'ordering': ['prefixo', 'tipo'],
            },
        ),
        migrations.AddField(
            model_name='distribuidora',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Endereco'),
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Estado'),
        ),
    ]
