# Generated by Django 2.1.5 on 2019-02-12 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Pagamento'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_notificacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Notificação'),
        ),
    ]
