# Generated by Django 2.1.5 on 2019-01-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_filme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='pais',
            field=models.CharField(max_length=150, verbose_name='País da Data de Lançamento'),
        ),
    ]
