# Generated by Django 2.1.5 on 2019-02-13 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190211_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': (('pode_ativar_cliente', 'Pode ativar um cliente'), ('pode_desativar_cliente', 'Pode desativar um cliente')), 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['data_aquisicao'], 'permissions': (('pode_ativar', 'Pode ativar um item'), ('pode_desativar', 'Pode desativar um item')), 'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
    ]
