# Generated by Django 2.1.5 on 2019-01-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190128_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Complemento'),
        ),
    ]
