# Generated by Django 2.1.5 on 2019-02-07 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190207_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacaopagamento',
            name='pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informacoes_pagamentos', to='core.Pagamento'),
        ),
    ]
