# Generated by Django 2.1.5 on 2019-02-04 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190204_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='is_lancamento',
            field=models.BooleanField(default=False, help_text='Designates whether this movie should be treated as release. Uncheck this if it is not a release.', verbose_name='release'),
        ),
    ]
