# Generated by Django 2.1.5 on 2019-02-13 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190213_0150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['data_aquisicao'], 'permissions': (('pode_ativar_item', 'Pode ativar um item'), ('pode_desativar_item', 'Pode desativar um item')), 'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
    ]
