# Generated by Django 2.1.5 on 2019-02-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190207_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this item should be treated as active. Unselect this instead of deleting items.', verbose_name='active'),
        ),
    ]
