# Generated by Django 2.1.5 on 2019-01-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190115_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='midia',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de Mídia', 'verbose_name_plural': 'Tipos de Mídias'},
        ),
        migrations.AlterField(
            model_name='midia',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor da Locação'),
        ),
    ]
