# Generated by Django 2.1.5 on 2019-02-04 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190204_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLocacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lancamento', models.BooleanField(default=False, help_text='Designa se este filme deve ser tratado como lançamento. Desmarque esta opção se não for um lançamento.', verbose_name='Lançamento')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor da Locação')),
                ('data_devolucao_prevista', models.DateField(blank=True, null=True, verbose_name='Data de Devolução Prevista')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Item')),
            ],
            options={
                'verbose_name': 'Item de Locação',
                'verbose_name_plural': 'Itens de Locação',
            },
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Valor Total da Locação')),
                ('data_locacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Locação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Cliente')),
            ],
            options={
                'verbose_name': 'Locação',
                'verbose_name_plural': 'Locações',
                'ordering': ['data_locacao'],
            },
        ),
        migrations.AlterField(
            model_name='filme',
            name='is_lancamento',
            field=models.BooleanField(default=False, help_text='Designa se este filme deve ser tratado como lançamento. Desmarque esta opção se não for um lançamento.', verbose_name='Lançamento'),
        ),
        migrations.AddField(
            model_name='itemlocacao',
            name='locacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Locacao'),
        ),
    ]
