# Generated by Django 2.1.5 on 2019-01-17 18:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190115_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaFilme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('tipo', multiselectfield.db.fields.MultiSelectField(choices=[('Diretor', 'Diretor'), ('Ator', 'Ator')], max_length=12, verbose_name='Classificação Indicativa')),
            ],
            options={
                'verbose_name': 'Pessoa do Filme',
                'verbose_name_plural': 'Pessoas dos Filmes',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='filme',
            name='diretor',
        ),
        migrations.AddField(
            model_name='filme',
            name='diretor',
            field=models.ManyToManyField(to='core.PessoaFilme'),
        ),
    ]
