# Generated by Django 2.1.5 on 2019-01-29 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_endereco_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(max_length=50, verbose_name='Bairro'),
        ),
    ]
