# Generated by Django 2.1.5 on 2019-02-13 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190213_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': (('pode_add_titular', 'Pode adicionar clientes titulares'), ('pode_change_titular', 'Pode editar clientes titulares'), ('pode_delete_titular', 'Pode excluir clientes titulares'), ('pode_view_titular', 'Pode visualizar clientes titulares'), ('pode_ativar_titular', 'Pode ativar clientes titulares'), ('pode_desativar_titular', 'Pode desativar clientes titulares'), ('pode_add_dependente', 'Pode adicionar dependentes'), ('pode_change_dependente', 'Pode editar dependentes'), ('pode_delete_dependente', 'Pode excluir dependentes'), ('pode_view_dependente', 'Pode visualizar dependentes'), ('pode_ativar_dependente', 'Pode ativar dependentes'), ('pode_desativar_dependente', 'Pode desativar dependentes')), 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('pode_add_funcionario', 'Pode adicionar funcionários'), ('pode_change_funcionario', 'Pode editar funcionários'), ('pode_delete_funcionario', 'Pode excluir funcionários'), ('pode_view_funcionario', 'Pode visualizar funcionários'), ('pode_ativar_funcionario', 'Pode ativar funcionários'), ('pode_desativar_funcionario', 'Pode desativar funcionários')), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
