# Generated by Django 2.1.5 on 2019-01-17 23:21

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190117_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personagem', models.CharField(max_length=150, verbose_name='Personagem')),
                ('principal', models.BooleanField(default=False, verbose_name='Principal ?')),
            ],
        ),
        migrations.AlterField(
            model_name='pessoafilme',
            name='tipo',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Diretor', 'Diretor'), ('Ator', 'Ator')], max_length=12, verbose_name='Atividade'),
        ),
        migrations.AddField(
            model_name='elenco',
            name='ator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PessoaFilme'),
        ),
        migrations.AddField(
            model_name='elenco',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Filme'),
        ),
    ]
