# Generated by Django 2.1.5 on 2019-02-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_locacao_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='situacao',
            field=models.CharField(choices=[('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída'), ('PAGA', 'Paga'), ('PAGA_PARCIAL', 'Paga Parcialmente'), ('CANCELADA', 'Cancelada')], default='EM_ANDAMENTO', max_length=20, verbose_name='Situação da Locação'),
        ),
    ]
