# Generated by Django 2.1.5 on 2019-02-13 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190213_0210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['data_reserva'], 'permissions': (('pode_cancelar_reserva', 'Pode cancelar reservas'),), 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reserva'},
        ),
    ]
