# Generated by Django 2.1.5 on 2019-02-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190213_0216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artista',
            options={'ordering': ['nome'], 'permissions': (('add_diretor', 'Pode adicionar diretores'), ('change_diretor', 'Pode editar diretores'), ('delete_diretor', 'Pode excluir diretores'), ('view_diretor', 'Pode visualizar diretores'), ('add_ator', 'Pode adicionar atores'), ('change_ator', 'Pode editar atores'), ('delete_ator', 'Pode excluir atores'), ('view_ator', 'Pode visualizar atores')), 'verbose_name': 'Artista', 'verbose_name_plural': 'Artistas'},
        ),
    ]
