# Generated by Django 2.1.5 on 2019-01-29 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas/', verbose_name='Capa do Filme'),
        ),
        migrations.AddField(
            model_name='filme',
            name='distribuidora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Distribuidora'),
        ),
    ]
