# Generated by Django 2.1.5 on 2019-01-22 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190117_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elenco',
            options={'ordering': ['ator', 'principal'], 'verbose_name': 'Elenco', 'verbose_name_plural': 'Elencos'},
        ),
        migrations.AlterUniqueTogether(
            name='elenco',
            unique_together={('filme', 'ator')},
        ),
    ]
