# Generated by Django 2.1.5 on 2019-02-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190213_0817'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['user__first_name'], 'permissions': (('pode_add_titular', 'Pode adicionar clientes titulares'), ('pode_change_titular', 'Pode editar clientes titulares'), ('pode_delete_titular', 'Pode excluir clientes titulares'), ('pode_view_titular', 'Pode visualizar clientes titulares'), ('pode_ativar_titular', 'Pode ativar clientes titulares'), ('pode_desativar_titular', 'Pode desativar clientes titulares'), ('pode_add_dependente', 'Pode adicionar dependentes'), ('pode_change_dependente', 'Pode editar dependentes'), ('pode_delete_dependente', 'Pode excluir dependentes'), ('pode_view_dependente', 'Pode visualizar dependentes'), ('pode_ativar_dependente', 'Pode ativar dependentes'), ('pode_desativar_dependente', 'Pode desativar dependentes')), 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Pagamento'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_notificacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Notificação'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='is_lancamento',
            field=models.BooleanField(default=False, help_text='Designa se este filme deve ser tratado como lançamento. Desmarque esta opção se não for um lançamento.', verbose_name='Lançamento?'),
        ),
    ]
