# Generated by Django 2.1.5 on 2019-02-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_item_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
