# Generated by Django 2.1.5 on 2019-01-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190122_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoafilme',
            name='nome',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome'),
        ),
    ]
