# Generated by Django 2.0.9 on 2019-02-16 19:49

from django.db import migrations, models
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password

# def save_dependences(apps, schema_editor):
#     # Obtendo models
#     User = apps.get_model(settings.AUTH_USER_MODEL)
#     Perfil = apps.get_model('core', 'Perfil')
#     Cliente = apps.get_model('core', 'Cliente')
#     Midia = apps.get_model('core', 'Midia')
#     Distribuidora = apps.get_model('core', 'Distribuidora')
#     Estado = apps.get_model('core', 'Estado')
#     Cidade = apps.get_model('core', 'Cidade')
#     Endereco = apps.get_model('core', 'Endereco')
#     Genero = apps.get_model('core', 'Genero')
#     Filme = apps.get_model('core', 'Filme')
#     Artista = apps.get_model('core', 'Artista')
#     Item = apps.get_model('core', 'Item')

#     genero, created_gen = Genero.objects.get_or_create(nome='Genero 1', slug='gen1')
#     # Criando usuário
#     try:
#         u = User.objects.get(email='teste@bdd.com')
#     except User.DoesNotExist:
#         u = User.objects.create(
#                 email='teste@bdd.com', password=make_password('123456'), first_name='teste', last_name="bdd",
#                 is_staff=True, is_superuser=True
#         )
#         Perfil.objects.create(user=u, cpf="32808972032",data_nascimento="2000-02-01", sexo='F')
#         # u.perfil.cpf = "32808972032"
#         # u.perfil.data_nascimento="2019-02-01"
#         # u.perfil.sexo="F"
#         # u.save()


#     # Criando cliente padrão
#     u_cliente, created = User.objects.get_or_create(
#         first_name='cliente', last_name='padrão', email='emaildocliente@bdd.com'
#     )
#     cliente, created_cli = Cliente.objects.get_or_create(user=u_cliente)

#     # Criando tipo de midia
#     midia, created_mid = Midia.objects.get_or_create(nome='DVD', valor=7.5)

#     # Estado cidade
#     estado, created_est = Estado.objects.get_or_create(nome='Pernambuco', sigla='PE')
#     cidade, created_cid = Cidade.objects.get_or_create(nome='Recife', capital=True, estado=estado)

#     #  Distribuidora
#     endereco, created_end = Endereco.objects.get_or_create(
#         logradouro='Endereço dist',
#         numero=10,
#         bairro='Bairro dist',
#         cep='66600111',
#         estado=estado,
#         cidade=cidade
#     )
#     distribuidora, created_dist = Distribuidora.objects.get_or_create(razao_social='Distribuidora 1', endereco=endereco)

#     # Filme
#     diretor, created_dir = Artista.objects.get_or_create(nome='Diretor 1')
#     ator, created_ator = Artista.objects.get_or_create(nome='Ator 1')

#     filme, created_fil = Filme.objects.get_or_create(
#         titulo='Filme 1', titulo_original='one movie', sinopse='Resumo',
#         classificacao='L',duracao='02:00', ano=2018,
#         distribuidora=distribuidora, is_lancamento=True
#     )

#     filme.genero.add(genero)
#     filme.diretor.add(diretor)
#     filme.save()

#     # Item

#     item, created = Item.objects.get_or_create(
#         numero_serie='1111111', data_aquisicao='2019-02-01', tipo_midia=midia, filme=filme
#     )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190217_0755'),
    ]

    # operations = [
    #     migrations.RunPython(save_dependences),
    # ]
