# Generated by Django 2.1.5 on 2019-02-06 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190205_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArgumentoPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argumento', models.CharField(max_length=100, verbose_name='Nome do argumento')),
                ('requerido', models.BooleanField(default=False, verbose_name='Argumento obrigatório?')),
                ('tipo_dado', models.IntegerField(choices=[('TEXTO', 'Texto'), ('INTEIRO', 'Inteiro'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('ARQUIVO', 'ARQUIVO')], verbose_name='Tipo de dado do argumento')),
            ],
            options={
                'verbose_name': 'Argumento do Pagamento',
                'verbose_name_plural': 'Argumentos dos Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, unique=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='InformacaoPagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_texto', models.TextField(blank=True, null=True, verbose_name='Valor da informação em Texto')),
                ('valor_inteiro', models.IntegerField(blank=True, null=True, verbose_name='Valor da informação em Número Inteiro')),
                ('valor_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da informação em Número Decimal')),
                ('valor_boolean', models.BooleanField(blank=True, null=True, verbose_name='Valor da informação Verdadeiro ou Falso')),
                ('valor_arquivo', models.FileField(blank=True, null=True, upload_to='arquivo_pessoa/', verbose_name='Valor da informação em Arquivo')),
                ('argumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informacoes_argumentos', to='core.ArgumentoPagamento')),
            ],
            options={
                'verbose_name': 'Informação do Pagamento',
                'verbose_name_plural': 'Informações dos Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateTimeField(auto_now_add=True, verbose_name='Data de Pagamento')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.FormaPagamento')),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Locacao')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de Cópias'),
        ),
        migrations.AddField(
            model_name='informacaopagamento',
            name='pagamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Pagamento'),
        ),
        migrations.AddField(
            model_name='argumentopagamento',
            name='forma_pagamento',
            field=models.ManyToManyField(to='core.FormaPagamento'),
        ),
    ]
