# Generated by Django 2.1.5 on 2019-02-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190206_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argumentopagamento',
            name='tipo_dado',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('INTEIRO', 'Inteiro'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('ARQUIVO', 'ARQUIVO')], max_length=20, verbose_name='Tipo de dado do argumento'),
        ),
    ]
