# Generated by Django 2.1.5 on 2019-02-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190206_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacaopagamento',
            name='valor_data_hora',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Valor da informação em Data/Hora'),
        ),
        migrations.AlterField(
            model_name='argumentopagamento',
            name='tipo_dado',
            field=models.CharField(choices=[('TEXTO', 'Texto'), ('INTEIRO', 'Inteiro'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Boolean'), ('DATA_HORA', 'Data/Hora'), ('ARQUIVO', 'Arquivo')], max_length=20, verbose_name='Tipo de dado do argumento'),
        ),
    ]
